### ISSUE TITLE
Add readme.md

### ISSUE THREAD

**Issue by DarkGuardsman** [ochotonida/candymod#3]
Should add a readme file to your github with basic information.

Example: https://github.com/BuiltBrokenModding/ICBM/blob/development/README.md

**Comment by Lemonszz** [comment]
Probably also worth adding a licence.
I suggest MIT, but find one that suits you.

Example: https://github.com/Lemonszz/Totem-Expansion/blob/master/LICENSE.md

**Comment by ochotonida** [comment]
Totally forgot about that, fixed it.
