### ISSUE TITLE
WorldGenGummyWorm can lock server thread

### ISSUE THREAD

**Issue by GoryMoon** [ochotonida/candymod#31]
MC: 1.12.2
Forge: 14.23.5.2847
CandyWorld: 1.1.4

Hi!

Darkosto has been using this mod in an upcoming Modpack where the world is generated as large hexes, we use your biomes for some of the hexes.
We have encountered a generation issue when a Gummy Swamp spawns next to a Void hex and the `WorldGenGummyWorm` happens to run on the edge of the biome the server thread enters an infinite loop.

With some debugging and thread dumping I've found that the [findSurfaceBlock()](https://github.com/ochotonida/candymod/blob/081791a26934c7a7e835e2cb4fd744f7f5b56011/src/main/java/com/ochotonida/candymod/world/worldgen/WorldGenGummyWorm.java#L43) method will run infinitely if it's over a Void. The `isAirBlock()` check in [isAirOrLiquid()](https://github.com/ochotonida/candymod/blob/081791a26934c7a7e835e2cb4fd744f7f5b56011/src/main/java/com/ochotonida/candymod/world/worldgen/WorldGenGummyWorm.java#L141) always returns true when below 0 so I suggest to add a check of Y being above 0.

I know this very special edge case and not intended by the mod but would appreciate it being fixed.

**Comment by ochotonida** [comment]
It should be fixed, although I didn't really do any testing. I've uploaded a patch to curseforge.
