### ISSUE TITLE
Crash with Primitive Mobs

### ISSUE THREAD

**Issue by WenXin20** [ochotonida/candymod#5]
Forge v14.23.3.2682
Primitive Mobs v1.1.6_beta
Candy World v0.4.3
I got a crash when a Rocket Creeper from Primitive Mobs exploded in the Cotton Candy biome.
[Crash Report](https://pastebin.com/Rkt2X9X4)

**Comment by ochotonida** [comment]
I will look into this issue when I have the time (which I currently don't) and I'll try to include a fix in the next update.

**Comment by WenXin20** [comment]
Ok, thank you!
